"""提示词模块"""
from .system_prompts import (
    AGENT_SYSTEM_PROMPT,
    PLANNING_PROMPT,
    EXECUTION_PROMPT,
    REPORT_GENERATION_PROMPT,
    ERROR_RECOVERY_PROMPT
)

__all__ = [
    "AGENT_SYSTEM_PROMPT",
    "PLANNING_PROMPT",
    "EXECUTION_PROMPT",
    "REPORT_GENERATION_PROMPT",
    "ERROR_RECOVERY_PROMPT"
]

